version: '3.8'

services:
  server:
    image: pwserver:latest
    build:
      context: ./
      dockerfile: ./pwserver/Dockerfile
    ports:
      - 8211:8211/udp
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
     - ./scripts/:/home/steam/scripts/
     - ./data/Saved:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved
    entrypoint: [
      "/home/steam/Steam/steamapps/common/PalServer/Pal/Binaries/Linux/PalServer-Linux-Test",
      "Pal",
      "-port=8211",
      "-players=16",
      "-useperfthreads",
      "-NoAsyncLoadingThread",
      "-UseMultithreadForDS",
      "-publicip=127.0.0.1",
      "-publicport=8211",
      #"EpicApp=PalServer",
      "-servername=Palworld Server",
      "-serverpassword=secure-password",
      "-adminpassword=admin-password"
    ]
volumes:
  pwserver_data:
    external: false
