version: '3.8'

services:
  server:
    image: pwserver:latest
    build:
      context: ./
      dockerfile: ./pwserver/Dockerfile
    ports:
      - 8211:8211/udp
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
     - ./scripts:/home/steam/scripts
     - ./config:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer
    entrypoint: [ 
      "/home/steam/Steam/steamapps/common/PalServer/PalServer.sh", 
      "--port", 
      "8211", 
      "--players", 
      "16", 
      "--useperfthreads",
      "-NoAsyncLoadingThread",
      "-UseMultithreadForDS"
    ]
volumes:
  pwserver_data:
    external: false
